import "dotenv/config";
import { Command, Option } from "commander";

import { version } from "./package.json";

const program = new Command();

program
  .name("string-util")
  .description("CoTask CLI - AI Assistant for coding tasks in your codebase.")
  .version(version);

program
  .command("run")
  .description("Runs a task defined by the user.")
  .argument(
    "<task definition>",
    "High level goals of the task, what you want to achieve.",
  )
  .addOption(
    new Option(
      "--unsafe-command",
      "Executes commands generated by CoTask without user approval.",
    ),
  )
  .action((taskDefinition: string) => {
    console.log("Running task with definition: ", taskDefinition);
    process.exit(0);
  });

program.parse();
